### PR TITLE
Portuguese language support

### PR DESCRIPTION
**Pull request by V-rtualized**

### CODE REVIEW

**Comment by tmetcalfe89** [comment]
@VirtualizedC Looks like `spawn_notification.notification.legendary` says `Shiny` in it.

**Comment by tmetcalfe89** [comment]
Also, thank you, this is awesome!

**Comment by V-rtualized** [comment]
> @VirtualizedC Looks like `spawn_notification.notification.legendary` says `Shiny` in it.

Ah yeah, my mistake, should be good now

**Comment by tmetcalfe89** [comment]
Would you like to be added to a CREDITS file?

**Pull request merged**
